name: GO2

on:
  push:
    branches: ["new_workflow"]

jobs:
  # Задание производит сборку приложения

  build:
    runs-on: ubuntu-latest
    # Шаги задания
    steps:
      # Первый шаг использует действие "actions/checkout@v3", которое извлекает репозиторий для дальнейшей работы с ним
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5

      # Шаг с именем "Build"
      - name: Build
        # Этот шаг просто выполняет команду 'go build -v ./...'
        run: go build -v ./...

  # Задание запускает тесты
  tests:
    # Задание "tests" зависит от задания "build" и будет выполнено после него
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      # Шаг с именем "Test"
      - name: Test
        # Этот шаг выполняет команду 'go test -v ./...'
        run: go test -v ./...

 